image: maven:3-jdk-8

stages:
- build
- tag
- deploy

FurnitureLib:
  stage: build
  script:
     - mvn clean package
  artifacts:
     paths:
     - target/*.jar
  only:
    - master
    
FurnitureLib-Nexus:
  stage: deploy
  script:
     - mvn deploy
  only:
    - master