image: maven:3-jdk-10

stages:
- build
- tag

FurnitureLib:
  stage: build
  script:
     - mvn clean package -Dfurniture.tag="-dev-$CI_COMMIT_SHORT_SHA"
  artifacts:
     paths:
     - target/FurnitureLib.jar
  only:
    - master